l_russian:
 
 
#中ベント#
aaa_weapon_event.1.t:0 "Целевая группа 404 не найдена"
aaa_weapon_event.1.d:0 "Целевая группа 404 прибыла. Командир, давайте с этого момента будем ладить\n\nUMP9 вернулся домой! Все, теперь мы одна семья!\n\N Вы командир? HK416......Пожалуйста, запомните это имя, это... необычное имя.\n\nG11...... Коммандер, здесь достаточно кроватей?"
 aaa_weapon_event.1.a:0 "добро пожаловать"
 
 #ディシジョン#
 
 404_решения:0 "Целевая группа"
 Task_Force_404_Heckler_und_Koch:0 "Целевая группа 404 не найдена"
 


 #特性#
 Leader_Infiltration_tactics:0 "Тактика проникновения"
 Leader_Infiltration_tactics_desc:0 ""
 Front_commander:0 "Командующий фронтом"
 Front_commander_desc:0 ""
 Храбрость:0 "Храбрость"
 Храбрость:0 ""
 Спокойнее:0 "Спокойнее"
 Calmer_desc:0 ""
 Сотрудник:0 "Сотрудник"
 Staffer_desc:0 ""
 Дисциплинарный работник:0 "Дисциплинарный работник"
 Disciplinarian_desc:0 ""
 Military_dictatorships:0 "Военные диктатуры"
 Military_dictatorships_desc:0 ""
 artillery_leader:0 "Руководитель артиллерии"
artillery_leader_desc:0 ""
 Heavy_attack:0 "Тяжелая атака"
 Heavy_attack_desc:0 ""
 Storm_eye:0 "Штормовой глаз"
 Storm_eye_desc:0 ""

 признак_404:0 "Целевая Группа 404 Не найдена"
 признак_404_desc:0 "404_not_found"
 404_tt:0 "Активная тактика:§YGhost Assalt§!\nRecon:§G+20%§!\Наттак:§G+1§!"
 leader_404:0 "Руководитель целевой группы 404"
 лидер_404_desc:0 "404_not_found"
 404_leader_tt:0 "Увеличена вероятность выполнения §HBlack Out§! тактика\nRecon:§G+20%§!\Наттак:§G+1§!"
 
 
 Признак_ар:0 "Целевая группа по борьбе с дождем"
 trait_AR_desc:0 "Оперативная группа "Анти-Дождь" - это элитное подразделение, которое может действовать независимо в течение длительного периода времени".
 trait_AR_tt:0 "Активная тактика:§Фокус на нанесении ущерба§!\nrecon:§G+20%§!\наттак:§G+1§!"
 тактика_404:0 "Затемнение"
 tactic_AR:0 "Фокус урона"